# Generated by Django 6.0.3 on 2026-03-14 01:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text="Введіть ім'я автора", max_length=100, verbose_name="Ім'я автора")),
                ('last_name', models.CharField(help_text='Введіть призвіще автора', max_length=100, verbose_name='Прізвище автора')),
                ('date_of_birth', models.DateField(blank=True, help_text='Введіть дату народження', null=True, verbose_name='Дата народження')),
                ('date_of_death', models.DateField(blank=True, help_text='Введіть дату смерті', null=True, verbose_name='Дата смерті')),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введіть жанр книги', max_length=200, verbose_name='Жанр книги')),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введіть мову книги', max_length=20, verbose_name='Мова книги')),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введіть статус екземпляру книги', max_length=20, verbose_name='Статус екземпляру')),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Введіть назву книги', max_length=200, verbose_name='Назва книги')),
                ('summary', models.TextField(help_text='Введіть короткий опис книги', max_length=1000, verbose_name='Аннотація до книги')),
                ('isbn', models.CharField(help_text='Має містити 13 символів', max_length=13, verbose_name='isbn книги')),
                ('author', models.ManyToManyField(help_text='Виберіть автора книги', null=True, to='catalog.author', verbose_name='Автор книги')),
                ('genre', models.ForeignKey(help_text='Виберіть жанр книги', null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.genre', verbose_name='Жанр книги')),
                ('language', models.ForeignKey(help_text='Виберіть мову книги', null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.language', verbose_name='Мова книги')),
            ],
        ),
        migrations.CreateModel(
            name='BookInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inv_num', models.CharField(help_text='Введіть інвентарний номер', max_length=20, null=True, verbose_name='Інвентарний номер')),
                ('imprint', models.CharField(help_text='Введіть видавництво і рік випуску', max_length=200, verbose_name='Видавництво')),
                ('due_back', models.DateField(blank=True, help_text='Введіть кінець строку статусу', null=True, verbose_name='Дата закінчення статусу')),
                ('book', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.book')),
                ('status', models.ForeignKey(help_text='Змінити статус екземпляру', null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.status', verbose_name='Статус')),
            ],
        ),
    ]
