# Generated by Django 6.0.3 on 2026-03-14 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.ManyToManyField(help_text='Виберіть автора книги', to='catalog.author', verbose_name='Автор книги'),
        ),
    ]
